from PyQt6 import QtCore, QtWidgets

# QtGui


class Ui_AstrOkay(object):
    def setupUi(self, AstrOkay):
        AstrOkay.setObjectName("AstrOkay")
        AstrOkay.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        AstrOkay.setEnabled(True)
        AstrOkay.resize(1440, 800)
        AstrOkay.setAutoFillBackground(False)
        AstrOkay.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=AstrOkay)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 110, 431, 731))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 270, 371, 177))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 3, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 0, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_11.setMouseTracking(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 1, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 3, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 0, 3, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout.addWidget(self.lcdNumber_3, 1, 3, 1, 1)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout.addWidget(self.lcdNumber_4, 2, 3, 1, 1)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.gridLayout.addWidget(self.lcdNumber_5, 3, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(parent=self.tab)
        self.line_4.setGeometry(QtCore.QRect(20, 450, 371, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.line = QtWidgets.QFrame(parent=self.tab)
        self.line.setGeometry(QtCore.QRect(20, 250, 371, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 150, 371, 91))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_3.addWidget(self.pushButton_30, 0, 2, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_3.addWidget(self.pushButton_29, 0, 1, 1, 1)
        self.lcdNumber_11 = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget_2)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.gridLayout_3.addWidget(self.lcdNumber_11, 0, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 2, 1, 1, 3)
        self.label_7 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(parent=self.tab)
        self.line_2.setGeometry(QtCore.QRect(20, 130, 371, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 110, 371, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 90, 371, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.tab)
        self.checkBox.setGeometry(QtCore.QRect(20, 70, 371, 20))
        self.checkBox.setObjectName("checkBox")
        self.line_3 = QtWidgets.QFrame(parent=self.tab)
        self.line_3.setGeometry(QtCore.QRect(20, 60, 371, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 371, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_2.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_2.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_2.addWidget(self.pushButton_18)
        self.lcdNumber_6 = QtWidgets.QLCDNumber(parent=self.horizontalLayoutWidget_2)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.horizontalLayout_2.addWidget(self.lcdNumber_6)
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=self.tab)
        self.verticalScrollBar.setGeometry(QtCore.QRect(400, 140, 16, 551))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(parent=self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 470, 371, 177))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_20 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_2.addWidget(self.pushButton_20, 2, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_2.addWidget(self.pushButton_21, 1, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_2.addWidget(self.pushButton_22, 3, 2, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_2.addWidget(self.pushButton_23, 3, 1, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_2.addWidget(self.pushButton_24, 0, 1, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_2.addWidget(self.pushButton_25, 1, 1, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_2.addWidget(self.pushButton_26, 0, 2, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_2.addWidget(self.pushButton_27, 2, 1, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_2.addWidget(self.pushButton_28, 1, 2, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_2.addWidget(self.pushButton_31, 2, 2, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_2.addWidget(self.pushButton_32, 0, 0, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_2.addWidget(self.pushButton_33, 3, 0, 1, 1)
        self.lcdNumber_7 = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget_3)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.gridLayout_2.addWidget(self.lcdNumber_7, 0, 3, 1, 1)
        self.lcdNumber_8 = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget_3)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.gridLayout_2.addWidget(self.lcdNumber_8, 1, 3, 1, 1)
        self.lcdNumber_9 = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget_3)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.gridLayout_2.addWidget(self.lcdNumber_9, 2, 3, 1, 1)
        self.lcdNumber_10 = QtWidgets.QLCDNumber(parent=self.gridLayoutWidget_3)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.gridLayout_2.addWidget(self.lcdNumber_10, 3, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 10, 81, 31))
        self.label.setObjectName("label")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(220, 10, 100, 32))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(120, 10, 100, 32))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 10, 100, 32))
        self.pushButton_15.setObjectName("pushButton_15")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(210, 40, 111, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 40, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 40, 51, 21))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 51, 21))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 60, 81, 21))
        self.label_3.setObjectName("label_3")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 60, 291, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        AstrOkay.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AstrOkay)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 24))
        self.menubar.setObjectName("menubar")
        self.menuWelcome_to_AstrOkay = QtWidgets.QMenu(parent=self.menubar)
        self.menuWelcome_to_AstrOkay.setObjectName("menuWelcome_to_AstrOkay")
        AstrOkay.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AstrOkay)
        self.statusbar.setObjectName("statusbar")
        AstrOkay.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuWelcome_to_AstrOkay.menuAction())

        self.retranslateUi(AstrOkay)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AstrOkay)
        print(self.pushButton_2.__class__)

    def retranslateUi(self, AstrOkay):
        _translate = QtCore.QCoreApplication.translate
        AstrOkay.setWindowTitle(_translate("AstrOkay", "MainWindow"))
        self.pushButton_4.setText(_translate("AstrOkay", "DarkFlat Frame "))
        self.pushButton_3.setText(_translate("AstrOkay", "Dark Frame"))
        self.pushButton_13.setText(_translate("AstrOkay", "Clean"))
        self.pushButton_9.setText(_translate("AstrOkay", "All"))
        self.pushButton_6.setText(_translate("AstrOkay", "All"))
        self.pushButton_7.setText(_translate("AstrOkay", "All"))
        self.pushButton_10.setText(_translate("AstrOkay", "Clean"))
        self.pushButton_8.setText(_translate("AstrOkay", "All"))
        self.pushButton_11.setText(_translate("AstrOkay", "Clean"))
        self.pushButton_12.setText(_translate("AstrOkay", "Clean"))
        self.pushButton_2.setText(_translate("AstrOkay", "Flat Frame "))
        self.pushButton_5.setText(_translate("AstrOkay", "Bias Frame"))
        self.pushButton.setText(_translate("AstrOkay", "   Ligth Frame   "))
        self.pushButton_30.setText(_translate("AstrOkay", "Clean"))
        self.pushButton_29.setText(_translate("AstrOkay", "All"))
        self.label_7.setText(_translate("AstrOkay", "Write Here:"))
        self.label_6.setText(_translate("AstrOkay", "What\'s You Procejt Name?"))
        self.checkBox_3.setText(_translate("AstrOkay", "Auto-Detect Master & Integrations"))
        self.checkBox_2.setText(_translate("AstrOkay", "Multi-Session Processing"))
        self.checkBox.setText(_translate("AstrOkay", "Multi-Channel/Filter Processing"))
        self.pushButton_16.setText(_translate("AstrOkay", "Your Frames"))
        self.pushButton_17.setText(_translate("AstrOkay", "All"))
        self.pushButton_18.setText(_translate("AstrOkay", "Clean"))
        self.pushButton_20.setText(_translate("AstrOkay", "Master DarkFlat"))
        self.pushButton_21.setText(_translate("AstrOkay", "Master Dark"))
        self.pushButton_22.setText(_translate("AstrOkay", "Clean"))
        self.pushButton_23.setText(_translate("AstrOkay", "All"))
        self.pushButton_24.setText(_translate("AstrOkay", "All"))
        self.pushButton_25.setText(_translate("AstrOkay", "All"))
        self.pushButton_26.setText(_translate("AstrOkay", "Clean"))
        self.pushButton_27.setText(_translate("AstrOkay", "All"))
        self.pushButton_28.setText(_translate("AstrOkay", "Clean"))
        self.pushButton_31.setText(_translate("AstrOkay", "Clean"))
        self.pushButton_32.setText(_translate("AstrOkay", "Master Flat"))
        self.pushButton_33.setText(_translate("AstrOkay", "Master Bias"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AstrOkay", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AstrOkay", "Tab 2"))
        self.label.setText(_translate("AstrOkay", "HDD .... GB"))
        self.pushButton_19.setText(_translate("AstrOkay", "Lisance"))
        self.pushButton_14.setText(_translate("AstrOkay", "Gpu/Cpu"))
        self.pushButton_15.setText(_translate("AstrOkay", "Config"))
        self.label_2.setText(_translate("AstrOkay", "APP %."))
        self.label_5.setText(_translate("AstrOkay", "STATUS"))
        self.label_4.setText(_translate("AstrOkay", "CPU %."))
        self.label_3.setText(_translate("AstrOkay", "OS %"))
        self.menuWelcome_to_AstrOkay.setTitle(_translate("AstrOkay", "Welcome to AstrOkay"))
        print(self.pushButton_2.__class__)
print(Ui_AstrOkay.retranslateUi)
print(Ui_AstrOkay.setupUi)